steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    for i in {1..3}; do
      gcloud functions deploy query_bigquery --runtime python39 --trigger-http --allow-unauthenticated --region $_REGION --source . --entry-point query_bigquery && break || sleep 15;
    done
  id: 'Deploy Function'
timeout: '1600s'
substitutions:
  _REGION: 'asia-east1'
