steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'sqlagenttest', '--runtime', 'python310', '--trigger-http', '--allow-unauthenticated', '--entry-point', 'query_bigquery']
