steps:
# Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-function', '.']

# Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-function']

# Deploy to Cloud Functions
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - functions
    - deploy
    - query_bigquery
    - --trigger-http
    - --runtime=python39
    - --entry-point=query_bigquery
    - --region=asia-east1
    - --source=.
    - --allow-unauthenticated
