swagger: "2.0"
info:
  title: API General
  description: "Ask ChatBot."
  version: "9.0.0"
host: api-gateway-7923qjyk.ue.gateway.dev
schemes:
  - "https"


security:
  - api_key: []
securityDefinitions:

   api_key:
     name: api_key
     type: apiKey
     in: query

paths:
  "/ask":
    post:
      
      x-google-backend:
        address: https://us-central1-fyp-open-data-hackathon.cloudfunctions.net/askchatbot
      description: "Get answer by asking ChatBot."
      operationId: "ask"
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              user_id:
                type: string
              data:
                type: object
                properties:
                  question:
                    type: string

      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
