openapi: "2.0"
info:
  title: API General
  description: "Ask ChatBot."
  version: "4.0.0"
host: api-gateway-7923qjyk.ue.gateway.dev
schemes:
  - "https"


security:
  - api_key: []
securityDefinitions:

   api_key:
     name: api_key
     type: apiKey
     in: query

paths:
  "/ask":
    POST:
      
      x-google-backend:
        address: https://us-central1-fyp-open-data-hackathon.cloudfunctions.net/askchatbot
      description: "Get answer by asking ChatBot."
      operationId: "ask"
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/schemas/ask'

      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "The message is invalid or missing."

schemas:
    ask:
      title: Asking ChatBot
      type: object
      properties:
        user_id:
          type: string
        data:
          type: object
          properties:
            question:
              type: string
      required:
        - data